### ISSUE TITLE
Adjust to the specific city's timezone

### ISSUE THREAD

**Issue by imwiss** [samchillcott/sam_react_weather_app#2]
As I was playing around with this app, I noticed that the time displayed are in UTC rather than in the specific city's timezone. I think it would be helpful to have them show up in the appropriate timezone.

Here's a screenshot showing the sunset and sunrise times for Montreal, Canada. Notice how the times are in UTC, which was quite confusing to me at first because our sunsets are not at midnight 😆 

![Screen Shot 2020-07-20 at 6 04 31 AM](https://user-images.githubusercontent.com/3534924/87926204-5b3a5c80-ca4f-11ea-9a75-0a3369092f7f.png)

If I have some free time this week, I might take a stab at submitting a PR for this.

**Comment by samchillcott** [comment]
Thanks for logging the issue, it has been great fun trying to get this working and given me some more experience with dates/times and libraries.

All sunrise and sunset times are now converted to local time (as opposed to UTC previously). Please see screenshot below:

![Screenshot 2020-08-14 at 10 25 42](https://user-images.githubusercontent.com/59138876/90235037-8d559900-de18-11ea-8a42-ff7349140aa1.png)
